# Generated by Django 2.2.5 on 2020-07-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
